# Generated by Django 4.0.6 on 2022-07-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(editable=False, max_length=4096)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=7, unique=True)),
                ('expiration_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
